//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblBeneficiary
    {
        [DataMember]
        public int beneficiary_id { get; set; }
        [DataMember]
        public Nullable<int> customer_id { get; set; }
        [DataMember]
        public Nullable<int> account_number { get; set; }
        [DataMember]
        public Nullable<int> beneficiary_account_number { get; set; }
        [DataMember]
        public string nickname { get; set; }
    
        public virtual tblBankingCustomer tblBankingCustomer { get; set; }
    }
}
