//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblBankingCustomers = new HashSet<tblBankingCustomer>();
        }
    
        public int Reference_id { get; set; }
        public string First_name { get; set; }
        public string middle_name { get; set; }
        public string Last_name { get; set; }
        public string Father_name { get; set; }
        public string mobile_number { get; set; }
        public string email_id { get; set; }
        public string account_type { get; set; }
        public string aadhar_number { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string Residential_address { get; set; }
        public string permanent_address { get; set; }
        public string occupation_Type { get; set; }
        public string source_of_income { get; set; }
        public double gross_income { get; set; }
        public Nullable<System.DateTime> account_OpenDate { get; set; }
        public string approved_status { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
    
        public virtual tbladmin tbladmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankingCustomer> tblBankingCustomers { get; set; }
    }
}
