//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocked
    {
        public Nullable<int> user_id { get; set; }
        public int account_number { get; set; }
    
        public virtual tblBankingCustomer tblBankingCustomer { get; set; }
    }
}
